name: "Release: Publish (TEST)"
run-name: "TEST: Multi-platform build"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Specify a tag to build from.

permissions:
  contents: read

jobs:
  PreRelease:
    uses: jericht/.github-aws-deadline/.github/workflows/reusable_maturin_prerelease.yml@jericht/reusable-maturin-build
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
